version: '2'

networks:
  my_network:

volumes:
  db:
  nextcloud:

services:
  db: 
    image: mariadb:10.6
    container_name: db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - my_network
    cpus: "1"
    mem_limit: 500M

  app:
    image: nextcloud
    container_name: nextcloud
    restart: always
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=password
    networks:
      - my_network
    cpus: "2"
    mem_limit: 2000M
    depends_on:
      - db
    
  locust:
    image: locustio/locust
    container_name: locust
    ports:
      - 8081:80
    volumes:
      - ./locust:/locust
    command: -f /locust/locustfile.py --host=http://nextcloud
    environment:
      - LOCUST_WEB_PORT=80
    networks:
      - my_network
    cpus: "1"
    mem_limit: 1500M
    depends_on:
      - app